language: java

jdk:
  - oraclejdk8

install: ./gradlew clean
script: ./gradlew test
deploy:
  - provider: script
    script: ./gradlew publishStubsPublicationToMavenRepository
cache:
  directories:
    - ~/.gradle/
