CREATE SEQUENCE SEQ_TEAM_MEMBER INCREMENT BY 1 MINVALUE 1 NO MAXVALUE START WITH 1000;

CREATE TABLE TEAM_MEMBER (
  ID              NUMERIC(8)  NOT NULL,
  OPEN_ID         VARCHAR(64) NOT NULL,
  VERSION         NUMERIC(8)  NOT NULL DEFAULT 1,
  DISPLAY_NAME    VARCHAR(128),
  REMAINING_LIVES INT         NOT NULL DEFAULT 0,
  CONSTRAINT PK_TEAM_MEMBER PRIMARY KEY (ID)
);
