CREATE TABLE TEAM_MEMBER (
  OPEN_ID         VARBINARY(16) NOT NULL,
  VERSION         NUMERIC(8)    NOT NULL DEFAULT 1,
  DISPLAY_NAME    VARCHAR(128),
  REMAINING_LIVES INT(2)        NOT NULL DEFAULT 0,
  CONSTRAINT PK_TEAM_MEMBER PRIMARY KEY (OPEN_ID)
);
