CREATE SEQUENCE SEQ_TEAM_MEMBER_EVENT increment BY 1 minvalue 1 NO MAXVALUE START WITH 1;

CREATE TABLE TEAM_MEMBER_EVENT (
  SEQUENCE NUMERIC(8)    NOT NULL,
  VERSION  NUMERIC(8)    NOT NULL,
  OPEN_ID  VARBINARY(16) NOT NULL,
  PAYLOAD  TEXT          NOT NULL,
  AT       DATETIME      NOT NULL,
  CONSTRAINT PK_TEAM_MEMBER_EVENT PRIMARY KEY (SEQUENCE)
);
