CREATE SEQUENCE SEQ_TEAM_MEMBER_EVENT INCREMENT BY 1 MINVALUE 1 NO MAXVALUE START WITH 1;

CREATE TABLE TEAM_MEMBER_EVENT (
  SEQUENCE       NUMERIC(8) NOT NULL,
  VERSION        NUMERIC(8) NOT NULL,
  TEAM_MEMBER_ID NUMERIC(8) NOT NULL,
  PAYLOAD        TEXT       NOT NULL,
  AT             TIMESTAMP   NOT NULL,
  CONSTRAINT PK_TEAM_MEMBER_EVENT PRIMARY KEY (SEQUENCE)
);
